logging.level.org.springframework: INFO

server:
 port: 8080

#spring:
# datasouce:
#  url: jdbc:postgresql://localhost:5432/SunFeedDB
#  username: postgres
#  password: 123456
#  driver-class-name: org.postgresql.Driver
 h2.console.enabled: true